### ISSUE TITLE
嘤

### ISSUE THREAD

**Issue by legends-killer** [lmx-Hexagram/Schedule_management#1]
带带我学py，嘤嘤嘤

**Comment by lmx-Hexagram** [comment]
嘤嘤嘤
只有第一个版本用的Python
现在是用Goland+Vue的
不如你教教我
怎么写前端

**Comment by legends-killer** [comment]
拉我进一波contributer如何嘤嘤嘤

**Comment by lmx-Hexagram** [comment]
okk

**Comment by lmx-Hexagram** [comment]
okk
可以运行的是master
现在最新的是dev3.0
dev3.0是重构了后端(接口不兼容了),前端还没来得及重构
