### ISSUE TITLE
v3.6的前端

### ISSUE THREAD

**Issue by lmx-Hexagram** [lmx-Hexagram/Schedule_management#3]
端口从`:1221`改成了`:12210`以后应该会一直使用`:12210`端口

邀请码暂时只支持数据库级修改

注册时需要在json中包含邀请码(详见API文档)

1. 注册和登陆界面(不要忘了输入邀请码的地方)
2. 合到master分支上
3. 有兴趣的话`readme.md`里添加一下自己的信息

后端已经测试过了,嘤该没什么问题

有bug随时叫我

**Comment by legends-killer** [comment]
目前在获取事务请求的api中出现跨域问题，应该需要后台解决

**Comment by lmx-Hexagram** [comment]
okk
